var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(na(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var oa=console.log.bind(console),k=console.error.bind(console),pa=!1,qa,na=a=>a.startsWith("file://"),ra=!1;
function ta(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),ua.push(...a));for(a=ua;a.length>0;)a.shift()(h)}function va(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),wa.push(...a));for(a=wa;a.length>0;)a.shift()(h)}function m(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var xa;
async function ya(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),m(d)}}
async function Aa(a){var b=xa;if(!na(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return za(b,a)}class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var wa=[],ua=[],p={},Ca=(a,b=[])=>{var c="vp".replace(/p/g,"i");(0,p[c])(a,...b)},Da=!1,Ea=globalThis.TextDecoder&&new TextDecoder,t=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ea)return Ea.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},v,w,Ga=()=>{var a=w[+Fa>>2];Fa+=4;return a},Ha=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ia=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Ha(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ka=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],La=(a,b)=>Ia(a+"/"+b),Ma=()=>{if(ca){var a=require("node:crypto");return b=>(a.randomFillSync(b),0)}return b=>(crypto.getRandomValues(b),0)},Na=a=>(Na=Ma())(a),Oa=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:x.cwd();if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Ha(b.split("/").filter(e=>
!!e),!c).join("/");return(c?"/":"")+b||"."},Pa=(a,b)=>{function c(g){for(var l=0;l<g.length&&g[l]==="";l++);for(var n=g.length-1;n>=0&&g[n]==="";n--);return l>n?[]:g.slice(l,n-l+1)}a=Oa(a).slice(1);b=Oa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Qa=[],Ra=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?
b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},y=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Sa=a=>{var b=Array(Ra(a)+1);a=y(a,b,0,b.length);b.length=
a;return b},Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],sf:b};Va(a,Wa)}
var Wa={open(a){var b=Ta[a.node.rdev];if(!b)throw new x.Pe(43);a.tty=b;a.seekable=!1},close(a){a.tty.sf.fsync(a.tty)},fsync(a){a.tty.sf.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.sf.Dg)throw new x.Pe(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.sf.Dg(a.tty)}catch(l){throw new x.Pe(29);}if(g===void 0&&e===0)throw new x.Pe(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.sf.kg)throw new x.Pe(60);try{for(var e=0;e<d;e++)a.tty.sf.kg(a.tty,
b[c+e])}catch(f){throw new x.Pe(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Xa={Dg(){a:{if(!Qa.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}Qa=Sa(a)}a=Qa.shift()}return a},kg(a,b){b===null||b===10?(oa(t(a.output)),a.output=[]):b!=
0&&a.output.push(b)},fsync(a){a.output?.length>0&&(oa(t(a.output)),a.output=[])},kh(){return{Jh:25856,Lh:5,Ih:191,Kh:35387,Hh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},mh(){return 0},nh(){return[24,80]}},Ya={kg(a,b){b===null||b===10?(k(t(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(k(t(a.output)),a.output=[])}},$a=a=>{a=Math.ceil(a/65536)*65536;var b=Za(65536,a);b&&v.fill(0,b,b+a);return b},z,B={mf:null,We(){return B.createNode(null,
"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||x.isFIFO(c))throw new x.Pe(63);B.mf||(B.mf={dir:{node:{gf:B.Qe.gf,nf:B.Qe.nf,lookup:B.Qe.lookup,qf:B.Qe.qf,rename:B.Qe.rename,unlink:B.Qe.unlink,rmdir:B.Qe.rmdir,readdir:B.Qe.readdir,symlink:B.Qe.symlink},stream:{Ye:B.Re.Ye}},file:{node:{gf:B.Qe.gf,nf:B.Qe.nf},stream:{Ye:B.Re.Ye,read:B.Re.read,write:B.Re.write,Af:B.Re.Af,Df:B.Re.Df}},link:{node:{gf:B.Qe.gf,nf:B.Qe.nf,readlink:B.Qe.readlink},stream:{}},xg:{node:{gf:B.Qe.gf,nf:B.Qe.nf},stream:x.Tg}});
c=x.createNode(a,b,c,d);C(c.mode)?(c.Qe=B.mf.dir.node,c.Re=B.mf.dir.stream,c.Se={}):x.isFile(c.mode)?(c.Qe=B.mf.file.node,c.Re=B.mf.file.stream,c.Ze=0,c.Se=B.Zg??(B.Zg=new Uint8Array(0))):(c.mode&61440)===40960?(c.Qe=B.mf.link.node,c.Re=B.mf.link.stream):(c.mode&61440)===8192&&(c.Qe=B.mf.xg.node,c.Re=B.mf.xg.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Se[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Qe:{gf(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=
0;b.gid=0;b.rdev=a.rdev;C(a.mode)?b.size=4096:x.isFile(a.mode)?b.size=a.Ze:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},nf(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.Ze!=b&&(c=a.Se,a.Se=new Uint8Array(b),a.Se.set(c.subarray(0,Math.min(b,a.Ze))),a.Ze=b))},lookup(){B.Xf||(B.Xf=new x.Pe(44),B.Xf.stack=
"<generic error, no stack>");throw B.Xf;},qf(a,b,c,d){return B.createNode(a,b,c,d)},rename(a,b,c){try{var d=ab(b,c)}catch(f){}if(d){if(C(a.mode))for(var e in d.Se)throw new x.Pe(55);bb(d)}delete a.parent.Se[a.name];b.Se[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Se[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=ab(a,b),d;for(d in c.Se)throw new x.Pe(55);delete a.Se[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Se)]},symlink(a,
b,c){a=B.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==40960)throw new x.Pe(28);return a.link}},Re:{read(a,b,c,d,e){if(e>=a.node.Ze)return 0;d=Math.min(a.node.Ze-e,d);b.set(a.node.Se.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.Se=b.subarray(c,c+d),a.Ze=d;else if(a.Ze===0&&e===0)a.Se=b.slice(c,c+d),a.Ze=d;else{f=e+d;var g=a.Se.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.Se.subarray(0,
a.Ze),a.Se=new Uint8Array(f),a.Se.set(g));a.Se.set(b.subarray(c,c+d),e);a.Ze=Math.max(a.Ze,e+d)}return d},Ye(a,b,c){c===1?b+=a.position:c===2&&x.isFile(a.node.mode)&&(b+=a.node.Ze);if(b<0)throw new x.Pe(28);return b},Af(a,b,c,d,e){if(!x.isFile(a.node.mode))throw new x.Pe(43);a=a.node.Se;if(e&2||a.buffer!==z.buffer){d=!0;e=$a(b);if(!e)throw new x.Pe(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{Kg:e,xf:d}},
Df(a,b,c,d){B.Re.write(a,b,0,d,c,!1);return 0}}},cb=a=>{typeof a=="string"&&(a=Sa(a));a.subarray||(a=new Uint8Array(a));return a},db=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},eb=async a=>{a=await ja(a);return new Uint8Array(a)},fb=null,gb=async()=>fb,hb=0,ib=null,jb=()=>{hb--;h.monitorRunDependencies?.(hb);hb||ib()},kb=()=>{hb||(fb=new Promise(a=>ib=a));hb++;h.monitorRunDependencies?.(hb)},lb=[],ob=async(a,b)=>{typeof mb!="undefined"&&nb();for(var c of lb)if(c.canHandle(b))return c.handle(a,
b);return a},qb=async(a,b,c,d,e,f,g,l)=>{var n=b?Oa(Ia(a+"/"+b)):a,q=`cp ${n}`;kb(q);try{var r=c;typeof c=="string"&&(r=await eb(c));r=await ob(r,n);l?.();f||pb(a,b,r,d,e,g)}finally{jb(q)}};function Va(a,b){x.Ag[a]={Re:b}}function C(a){return(a&61440)===16384}function ab(a,b){var c=C(a.mode)?(c=rb(a,"x"))?c:a.Qe.lookup?0:2:54;if(c)throw new x.Pe(c);for(c=x.rf[sb(a.id,b)];c;c=c.Bf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return x.lookup(a,b)}
function bb(a){var b=sb(a.parent.id,a.name);if(x.rf[b]===a)x.rf[b]=a.Bf;else for(b=x.rf[b];b;){if(b.Bf===a){b.Bf=a.Bf;break}b=b.Bf}}function pb(a,b,c,d,e,f){var g=b;a&&(a=typeof a=="string"?a:tb(a),g=b?Ia(a+"/"+b):a);a=db(d,e);g=x.create(g,a);c&&(c=cb(c),x.chmod(g,a|146),b=x.open(g,577),x.write(b,c,0,c.length,0,f),x.close(b),x.chmod(g,a))}
function D(a,b={}){if(!a)throw new x.Pe(44);b.Mf??(b.Mf=!0);a.charAt(0)==="/"||(a=x.cwd()+"/"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(l=>!!l);for(var d=x.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Ja(e),x.eg(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ia(e+"/"+a[f]);try{d=ab(d,a[f])}catch(l){if(l?.Te===44&&g&&b.qh)return{path:e};throw l;}!d.jf||g&&!b.Mf||(d=d.jf.root);if((d.mode&61440)===40960&&
(!g||b.ff)){if(!d.Qe.readlink)throw new x.Pe(52);d=d.Qe.readlink(d);d.charAt(0)==="/"||(d=Ja(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new x.Pe(32);}function tb(a){for(var b;;){if(x.eg(a))return a=a.We.Hg,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function sb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%x.rf.length}function ub(a){var b=sb(a.parent.id,a.name);a.Bf=x.rf[b];x.rf[b]=a}
function rb(a,b){return x.Eg?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function vb(a,b){if(!C(a.mode))return 54;try{return ab(a,b),20}catch(c){}return rb(a,"wx")}function wb(a,b,c){try{var d=ab(a,b)}catch(e){return e.Te}if(a=rb(a,"wx"))return a;if(c){if(!C(d.mode))return 54;if(x.eg(d)||tb(d)===x.cwd())return 10}else if(C(d.mode))return 31;return 0}function xb(a,b){if(!a)throw new x.Pe(b);return a}
function E(a){a=x.gh(a);if(!a)throw new x.Pe(8);return a}function yb(a,b=-1){a=Object.assign(new x.Qg,a);if(b==-1)a:{for(b=0;b<=x.Rg;b++)if(!x.streams[b])break a;throw new x.Pe(33);}a.fd=b;return x.streams[b]=a}function zb(a,b=-1){a=yb(a,b);a.Re?.Th?.(a);return a}function Ab(a,b,c){var d=a?.Re.nf;a=d?a:b;d??=b.Qe.nf;xb(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new x.Pe(22);throw e;}}function Bb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Ff)}return b}
function Cb(a){var b={Gh:4096,Xh:4096,blocks:1E6,Fh:5E5,Eh:5E5,files:x.ig,Vh:x.ig-1,Yh:42,flags:2,gi:255};a.Qe.Lg&&Object.assign(b,a.Qe.Lg(a.We.sh.root));return b}function Db(a,b,c){typeof c=="undefined"&&(c=b,b=438);return x.qf(a,b|8192,c)}function Eb(a,b,c,d){Ab(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Yf:d})}function Fb(a,b,c){if(C(b.mode))throw new x.Pe(31);if(!x.isFile(b.mode))throw new x.Pe(28);var d=rb(b,"w");if(d)throw new x.Pe(d);Ab(a,b,{size:c,timestamp:Date.now()})}
function Gb(a,b){a=typeof a=="string"?a:tb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ia(a+"/"+c);try{x.mkdir(d)}catch(e){if(e.Te!=20)throw e;}a=d}}return d}function Hb(a,b,c,d){a=typeof a=="string"?a:tb(a);b=Ia(a+"/"+b);return x.create(b,db(c,d))}
function Ib(a){if(!(a.oh||a.ph||a.link||a.Se))if(globalThis.XMLHttpRequest)m("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Se=ka(a.url)}catch(b){throw new x.Pe(29);}}
function Jb(a,b,c,d,e){function f(r,u,A,I,K){r=r.node.Se;if(K>=r.length)return 0;I=Math.min(r.length-K,I);if(r.slice)for(var N=0;N<I;N++)u[A+N]=r[K+N];else for(N=0;N<I;N++)u[A+N]=r.get(K+N);return I}class g{Vf=!1;bf=[];Uf=void 0;tg=0;sg=0;get(r){if(!(r>this.length-1||r<0)){var u=r%this.chunkSize;return this.Uf(r/this.chunkSize|0)[u]}}Sg(r){this.Uf=r}ug(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);r.status>=200&&r.status<300||r.status===304||m(`Couldn't load ${c}. Status: ${r.status}`);
var u=Number(r.getResponseHeader("Content-length")),A,I=(A=r.getResponseHeader("Accept-Ranges"))&&A==="bytes";r=(A=r.getResponseHeader("Content-Encoding"))&&A==="gzip";var K=1048576;I||(K=u);var N=this;N.Sg(la=>{var sa=la*K,ma=(la+1)*K-1;ma=Math.min(ma,u-1);if(typeof N.bf[la]=="undefined"){var Vb=N.bf;sa>ma&&m(`invalid range (${sa}, ${ma}) or no bytes requested!`);ma>u-1&&m(`only ${u} bytes available! programmer error!`);var R=new XMLHttpRequest;R.open("GET",c,!1);u!==K&&R.setRequestHeader("Range",
`bytes=${sa}-${ma}`);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");R.send(null);R.status>=200&&R.status<300||R.status===304||m(`Couldn't load ${c}. Status: ${R.status}`);sa=R.response!==void 0?new Uint8Array(R.response||[]):Sa(R.responseText??"");Vb[la]=sa}typeof N.bf[la]=="undefined"&&m("doXHR failed!");return N.bf[la]});if(r||!u)K=u=1,K=u=this.Uf(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");
this.tg=u;this.sg=K;this.Vf=!0}get length(){this.Vf||this.ug();return this.tg}get chunkSize(){this.Vf||this.ug();return this.sg}}if(globalThis.XMLHttpRequest){ba||m("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var l=new g;var n=void 0}else n=c,l=void 0;var q=Hb(a,b,d,e);l?q.Se=l:n&&(q.Se=null,q.url=n);Object.defineProperties(q,{Ze:{get:function(){return this.Se.length}}});a={};for(let [r,u]of Object.entries(q.Re))a[r]=(...A)=>
{Ib(q);return u(...A)};a.read=(r,u,A,I,K)=>{Ib(q);return f(r,u,A,I,K)};a.Af=(r,u,A)=>{Ib(q);var I=$a(u);if(!I)throw new x.Pe(48);f(r,z,I,u,A);return{Kg:I,xf:!0}};q.Re=a;return q}
var x={root:null,Ff:[],Ag:{},streams:[],ig:1,rf:null,yg:"/",cg:!1,Eg:!0,eh:null,Tf:0,Pe:class{name="ErrnoError";constructor(a){this.Te=a}},Qg:class{shared={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},Pg:class{Qe={};Re={};jf=null;listeners=null;bf=0;constructor(a,b,c,d){a||=this;this.parent=a;this.We=a.We;this.id=x.ig++;this.name=
b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get ph(){return C(this.mode)}get oh(){return(this.mode&61440)===8192}rh(){if(this.listeners){var a;for(b of this.listeners)b.exclusive?(a||=[]).push(b):b.cb(32);if(a){var b=(this.bf||0)%a.length;this.bf=b+1;a[b].cb(32)}}}},createNode(a,b,c,d){a=new x.Pg(a,b,c,d);
ub(a);return a},eg(a){return a===a.parent},isFile(a){return(a&61440)===32768},isFIFO(a){return(a&61440)===4096},isSocket(a){return(a&49152)===49152},Rg:4096,gh:a=>x.streams[a],Tg:{open(a){a.Re=x.fh(a.node.rdev).Re;a.Re.open?.(a)},Ye(){throw new x.Pe(70);}},gg:a=>a>>8,bi:a=>a&255,zf:(a,b)=>a<<8|b,fh:a=>x.Ag[a],Mg(a,b){function c(l){x.Tf--;return b(l)}function d(l){if(l){if(!d.ah)return d.ah=!0,c(l)}else++f>=e.length&&c(null)}typeof a=="function"&&(b=a,a=!1);x.Tf++;x.Tf>1&&k(`warning: ${x.Tf} FS.syncfs operations in flight at once, probably just doing extra work`);
var e=Bb(x.root.We),f=0,g;for(g of e)g.type.Mg?g.type.Mg(g,a,d):d(null)},We(a,b,c){var d=c==="/";if(d&&x.root)throw new x.Pe(10);if(!d&&c){var e=D(c,{Mf:!1});c=e.path;e=e.node;if(e.jf)throw new x.Pe(10);if(!C(e.mode))throw new x.Pe(54);}b={type:a,sh:b,Hg:c,Ff:[]};a=a.We(b);a.We=b;b.root=a;d?x.root=a:e&&(e.jf=b,e.We&&e.We.Ff.push(b));return a},ri(a){a=D(a,{Mf:!1});if(!a.node.jf)throw new x.Pe(28);a=a.node;var b=a.jf,c=Bb(b);for([,e]of Object.entries(x.rf))for(;e;){var d=e.Bf;c.includes(e.We)&&bb(e);
var e=d}a.jf=null;a.We.Ff.splice(a.We.Ff.indexOf(b),1)},lookup(a,b){return a.Qe.lookup(a,b)},qf(a,b,c){var d=D(a,{parent:!0}).node;a=Ka(a);if(!a)throw new x.Pe(28);if(a==="."||a==="..")throw new x.Pe(20);var e=vb(d,a);if(e)throw new x.Pe(e);if(!d.Qe.qf)throw new x.Pe(63);return d.Qe.qf(d,a,b,c)},Lg(a){return Cb(D(a,{ff:!0}).node)},oi(a){return Cb(a.node)},create(a,b=438){return x.qf(a,b&4095|32768,0)},mkdir(a,b=511){return x.qf(a,b&1023|16384,0)},ei(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||
a.charAt(0)==="/")d+="/";d+=e;try{x.mkdir(d,b)}catch(f){if(f.Te!=20)throw f;}}},symlink(a,b){if(!Oa(a))throw new x.Pe(44);var c=D(b,{parent:!0}).node;if(!c)throw new x.Pe(44);b=Ka(b);var d=vb(c,b);if(d)throw new x.Pe(d);if(!c.Qe.symlink)throw new x.Pe(63);return c.Qe.symlink(c,b,a)},link(a,b,c){var d=D(b,{parent:!0}).node;if(!d)throw new x.Pe(44);b=Ka(b);var e=vb(d,b);if(e)throw new x.Pe(e);if(!d.Qe.link)throw new x.Pe(34);return d.Qe.link(d,b,a,c)},rename(a,b){var c=Ja(a),d=Ja(b),e=Ka(a),f=Ka(b);
var g=D(a,{parent:!0});var l=g.node;g=D(b,{parent:!0});g=g.node;if(!l||!g)throw new x.Pe(44);if(l.We!==g.We)throw new x.Pe(75);var n=ab(l,e);a=Pa(a,d);if(a.charAt(0)!==".")throw new x.Pe(28);a=Pa(b,c);if(a.charAt(0)!==".")throw new x.Pe(55);try{var q=ab(g,f)}catch(r){}if(n!==q){b=C(n.mode);if(e=wb(l,e,b))throw new x.Pe(e);if(e=q?wb(g,f,b):vb(g,f))throw new x.Pe(e);if(!l.Qe.rename)throw new x.Pe(63);if(n.jf||q&&q.jf)throw new x.Pe(10);if(g!==l&&(e=rb(l,"w")))throw new x.Pe(e);bb(n);try{l.Qe.rename(n,
g,f),n.parent=g}catch(r){throw r;}finally{ub(n)}}},rmdir(a){var b=D(a,{parent:!0}).node;a=Ka(a);var c=ab(b,a),d=wb(b,a,!0);if(d)throw new x.Pe(d);if(!b.Qe.rmdir)throw new x.Pe(63);if(c.jf)throw new x.Pe(10);b.Qe.rmdir(b,a);bb(c)},readdir(a){a=D(a,{ff:!0}).node;return xb(a.Qe.readdir,54)(a)},unlink(a){var b=D(a,{parent:!0}).node;if(!b)throw new x.Pe(44);a=Ka(a);var c=ab(b,a),d=wb(b,a,!1);if(d)throw new x.Pe(d);if(!b.Qe.unlink)throw new x.Pe(63);if(c.jf)throw new x.Pe(10);b.Qe.unlink(b,a);bb(c)},readlink(a){a=
D(a).node;if(!a)throw new x.Pe(44);if(!a.Qe.readlink)throw new x.Pe(28);return a.Qe.readlink(a)},stat(a,b){a=D(a,{ff:!b}).node;return xb(a.Qe.gf,63)(a)},fstat(a){var b=E(a);a=b.node;var c=b.Re.gf;b=c?b:a;c??=a.Qe.gf;xb(c,63);return c(b)},lstat(a){return x.stat(a,!0)},chmod(a,b,c){a=typeof a=="string"?D(a,{ff:!c}).node:a;Eb(null,a,b,c)},lchmod(a,b){x.chmod(a,b,!0)},fchmod(a,b){a=E(a);Eb(a,a.node,b,!1)},chown(a,b,c,d){a=typeof a=="string"?D(a,{ff:!d}).node:a;Ab(null,a,{timestamp:Date.now(),Yf:d})},
lchown(a,b,c){x.chown(a,b,c,!0)},fchown(a){a=E(a);Ab(a,a.node,{timestamp:Date.now(),Yf:!1})},truncate(a,b){if(b<0)throw new x.Pe(28);a=typeof a=="string"?D(a,{ff:!0}).node:a;Fb(null,a,b)},Zh(a,b){a=E(a);if(b<0||(a.flags&2097155)===0)throw new x.Pe(28);Fb(a,a.node,b)},si(a,b,c,d){a=D(a,{ff:!d});Ab(null,a.node,{atime:b,mtime:c,Yf:d})},open(a,b,c=438){if(a==="")throw new x.Pe(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);
b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=D(a,{ff:!(b&131072),qh:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new x.Pe(20);}else{if(e)throw new x.Pe(31);d=x.qf(a,c|511,0);f=!0}if(!d)throw new x.Pe(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!C(d.mode))throw new x.Pe(54);if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=C(d.mode)&&(e!=="r"||b&576)?31:rb(d,e)):e=44,e))throw new x.Pe(e);b&512&&!f&&x.truncate(d,0);
b&=-131713;b=yb({node:d,path:tb(d),flags:b,seekable:!0,position:0,Re:d.Re,zh:[],error:!1});b.Re.open&&b.Re.open(b);f&&x.chmod(d,c&511);return b},close(a){if(a.fd===null)throw new x.Pe(8);a.yf&&(a.yf=null);a.node?.rh();try{a.Re.close&&a.Re.close(a)}catch(b){throw b;}finally{x.streams[a.fd]=null}a.fd=null},Ye(a,b,c){if(a.fd===null)throw new x.Pe(8);if(!a.seekable||!a.Re.Ye)throw new x.Pe(70);if(c!=0&&c!=1&&c!=2)throw new x.Pe(28);a.position=a.Re.Ye(a,b,c);a.zh=[];return a.position},read(a,b,c,d,e){if(d<
0||e<0)throw new x.Pe(28);if(a.fd===null)throw new x.Pe(8);if((a.flags&2097155)===1)throw new x.Pe(8);if(C(a.node.mode))throw new x.Pe(31);if(!a.Re.read)throw new x.Pe(28);var f=typeof e!="undefined";if(!f)e=a.position;else if(!a.seekable)throw new x.Pe(70);b=a.Re.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(d<0||e<0)throw new x.Pe(28);if(a.fd===null)throw new x.Pe(8);if((a.flags&2097155)===0)throw new x.Pe(8);if(C(a.node.mode))throw new x.Pe(31);if(!a.Re.write)throw new x.Pe(28);
a.seekable&&a.flags&1024&&x.Ye(a,0,2);var g=typeof e!="undefined";if(!g)e=a.position;else if(!a.seekable)throw new x.Pe(70);b=a.Re.write(a,b,c,d,e,f);g||(a.position+=b);return b},Af(a,b,c,d,e){if((d&2)!==0&&(e&2)===0&&(a.flags&2097155)!==2)throw new x.Pe(2);if((a.flags&2097155)===1)throw new x.Pe(2);if(!a.Re.Af)throw new x.Pe(43);if(!b)throw new x.Pe(28);return a.Re.Af(a,b,c,d,e)},Df(a,b,c,d,e){return a.Re.Df?a.Re.Df(a,b,c,d,e):0},dg(a,b,c){if(!a.Re.dg)throw new x.Pe(59);return a.Re.dg(a,b,c)},readFile(a,
b={}){b.flags=b.flags??0;b.encoding=b.encoding??"binary";b.encoding!=="utf8"&&b.encoding!=="binary"&&m(`Invalid encoding type "${b.encoding}"`);var c=x.open(a,b.flags);a=x.stat(a).size;var d=new Uint8Array(a);x.read(c,d,0,a,0);b.encoding==="utf8"&&(d=t(d));x.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags??577;a=x.open(a,c.flags,c.mode);b=cb(b);x.write(a,b,0,b.byteLength,void 0,c.Mh);x.close(a)},cwd:()=>x.yg,chdir(a){a=D(a,{ff:!0});if(a.node===null)throw new x.Pe(44);if(!C(a.node.mode))throw new x.Pe(54);
var b=rb(a.node,"x");if(b)throw new x.Pe(b);x.yg=a.path},init(a,b,c){x.cg=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?x.uf("/dev","stdin",a):x.symlink("/dev/tty","/dev/stdin");b?x.uf("/dev","stdout",null,b):x.symlink("/dev/tty","/dev/stdout");c?x.uf("/dev","stderr",null,c):x.symlink("/dev/tty1","/dev/stderr");x.open("/dev/stdin",0);x.open("/dev/stdout",1);x.open("/dev/stderr",1)},Wh(a,b){try{var c=D(a,{ff:!b});a=c.path}catch(f){}var d=!1,e=null;try{c=D(a,{parent:!0}),Ka(a),c=D(a,{ff:!b}),d=!0,e=c.node}catch(f){}return d?
e:null},uf(a,b,c,d){a=La(typeof a=="string"?a:tb(a),b);b=db(!!c,!!d);var e;(e=x.uf).gg??(e.gg=64);e=x.zf(x.uf.gg++,0);Va(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var q=0,r=0;r<n;r++){try{var u=c()}catch(A){throw new x.Pe(29);}if(u===void 0&&q===0)throw new x.Pe(6);if(u===null||u===void 0)break;q++;g[l+r]=u}q&&(f.node.atime=Date.now());return q},write(f,g,l,n){for(var q=0;q<n;q++)try{d(g[l+q])}catch(r){throw new x.Pe(29);}n&&(f.node.mtime=f.node.ctime=Date.now());
return q}});return Db(a,b,e)}},F,G;function Kb(a,b){if(b.charAt(0)==="/")return b;a=a===-100?x.cwd():E(a).path;if(b.length==0)throw new x.Pe(44);return a+"/"+b}
var Fa=void 0,H,Lb=a=>{a instanceof Ba||a=="unwind"||fa(1,a)},J=0,Pb=a=>{qa=a;if(!(Da||J>0)){Mb();for(var b=Nb;b.length>0;)b.shift()(h);x.cg=!1;Ob(0);for(var c of x.streams)c&&x.close(c);ra=!0}qa=a;Da||J>0||(h.onExit?.(a),pa=!0);fa(a,new Ba(a))},Qb=()=>{if(!(ra||Da||J>0))try{Pb(qa)}catch(a){Lb(a)}},Rb=a=>{if(!ra&&!pa)try{return a()}catch(b){Lb(b)}finally{Qb()}},Sb=a=>{J+=1;setTimeout(()=>{--J;Rb(a)},1E4)},Tb=!1,Ub=!1,Wb=[];
function nb(){function a(){Ub=document.pointerLockElement===h.canvas}if(!Xb){Xb=!0;lb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:Yb(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Yb(d)}));var f=URL.createObjectURL(e);return new Promise((g,l)=>{var n=new Image;n.onload=()=>{var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(f);
g(c)};n.onerror=()=>{k(`Image ${f} could not be decoded`);l()};n.src=f})}});lb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,l=new Blob([c],{type:Yb(d)});l=URL.createObjectURL(l);var n=new Audio;n.addEventListener("canplaythrough",()=>f(n));n.onerror=()=>{if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var q="data:audio/x-"+d.slice(-3)+";base64,",
r="",u=0,A=0,I=0;I<c.length;I++)for(u=u<<8|c[I],A+=8;A>=6;){var K=u>>A-6&63;A-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[K]}A==2?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],r+="=="):A==4&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],r+="=");n.src=q+r;f(n)}};n.src=l;Sb(()=>{f(n)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a),h.elementPointerLock&&b.addEventListener("click",
c=>{!Ub&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())}))}}function Zb(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Gg:1};if(d)for(var g in d)f[g]=d[g];if(typeof $b!="undefined"&&(e=ac(a,f)))var l=bc[e].tf}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&cc(e),Wb.forEach(n=>n()),nb());return l}var dc=!1,ec=void 0,fc=void 0;
function hc(){if(!Tb)return!1;(document.exitFullscreen??document.webkitCancelFullScreen).apply(document,[]);return!0}function Yb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var ic=[];function jc(){var a=h.canvas;ic.forEach(b=>b(a.width,a.height))}
function kc(a){if(b&&c)a.Bh=b,a.hh=c;else{var b=a.Bh;var c=a.hh}var d=b,e=c;if((document.fullscreenElement??document.webkitFullscreenElement)===a.parentNode&&typeof screen!="undefined"){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}fc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),typeof a.style!="undefined"&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),typeof a.style!="undefined"&&(d!=
b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var mb={},Xb,L=12288,lc=!1,mc=0,nc=0,oc=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},pc={},qc,O,rc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},sc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},tc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},uc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},vc=1,wc=[],P=[],xc=[],yc=[],zc=[],Q=[],Ac=[],bc=[],Bc=[],Cc={},Dc=4,Ec=0,Fc=a=>{for(var b=vc++,c=a.length;c<b;c++)a[c]=null;return b},Gc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=O[c](),g=f&&Fc(d);f?(f.name=g,d[g]=f):S||=1282;w[b+e*4>>2]=g}},ac=(a,b)=>{a.bf||(a.bf=a.getContext,a.getContext=function(d,e){e=a.bf(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Hc(c,b):0},Hc=(a,b)=>
{var c=Fc(bc),d={handle:c,attributes:b,version:b.Gg,tf:a};a.canvas&&(a.canvas.Ef=d);bc[c]=d;if(typeof b.$g=="undefined"||b.$g)if((a=d)||(a=Ic),!a.jh){a.jh=!0;a=a.tf;a.fi=a.getExtension("WEBGL_multi_draw");a.dh=a.getExtension("EXT_polygon_offset_clamp");a.bh=a.getExtension("EXT_clip_control");a.Ah=a.getExtension("WEBGL_polygon_mode");rc(a);sc(a);tc(a);a.pf=a.getExtension("EXT_disjoint_timer_query");for(var e of uc(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},cc=a=>
{Ic=bc[a];h.ctx=O=Ic?.tf},$b={},S,Ic,Jc=a=>{var b=Ra(a)+1,c=T(b);c&&y(a,v,c,b);return c},$c=(a,b,c,d,e)=>{function f(){return g<Kc?(--J,Qb(),!1):!0}Lc=a;Mc=d;var g=Kc;Nc=!1;Oc=function(){if(!pa)if(Pc.length>0){var l=Pc.shift();l.$h(l.Ch);if(Qc){var n=Qc,q=n%1==0?n-1:Math.floor(n);Qc=l.Ph?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Qc??0,q=Rc.Uh??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(Oc,0)}else if(f())if(Sc=
Sc+1|0,Tc==1&&Uc>1&&Sc%Uc!=0)Vc();else{Tc==0&&(Wc=performance.now());a:if(!pa){for(l of Xc)if(l()===!1)break a;Rb(a);for(n of Yc)n()}f()&&Vc()}};e||(b>0?Zc(0,1E3/b):Zc(1,1),Vc());if(c)throw"unwind";},Nc=!1,Vc=null,Kc=0,Lc=null,Mc=0,Tc=0,Uc=0,Sc=0,Pc=[],Xc=[],Yc=[];function ad(){Vc=null;Kc++}function bd(){Kc++;var a=Tc,b=Uc,c=Lc;Lc=null;$c(c,0,!1,Mc,!0);Zc(a,b);Vc()}var cd=0;
function dd(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(cd===0)cd=b+1E3/60;else for(;b+2>=cd;)cd+=1E3/60;setTimeout(a,Math.max(cd-b,0))}}
var Rc={},Oc,Qc,Wc,ed,Zc=(a,b)=>{Tc=a;Uc=b;if(Lc)if(Nc||(J+=1,Nc=!0),a==0)Vc=function(){setTimeout(Oc,Math.max(0,Wc+b-performance.now())|0)};else if(a==1)Vc=function(){dd(Oc)};else{if(!ed)if(globalThis.scheduler)ed=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)ed=setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);ed=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}Vc=function(){ed(Oc)}}},
fd=[],U,gd=(a,b)=>{fd.length=0;for(var c;c=v[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;fd.push(c==112?F[b>>2]:c==106?G[b>>3]:c==105?w[b>>2]:U[b>>3]);b+=d?8:4}return fd},Nb=[];function hd(a){var b=V.af[a];b.target.removeEventListener(b.Xe,b.Bg,b.df);V.af.splice(a,1)}function jd(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of V.wf)if(e.mg==a&&d(e.vg,c))return;V.wf.push({mg:a,Jg:b,vg:c});V.wf.sort((f,g)=>f.Jg-g.Jg)}
function kd(a){V.wf=V.wf.filter(b=>b.mg!=a)}function ld(){return navigator.userActivation?navigator.userActivation.isActive:V.bg&&V.Vg.Hf}function md(){if(ld()){var a=V.wf;V.wf=[];for(var b of a)b.mg(...b.vg)}}function nd(a){if(!a.target)return-4;if(a.$e)a.Bg=function(c){++V.bg;V.Vg=a;md();a.hf(c);md();--V.bg},a.target.addEventListener(a.Xe,a.Bg,a.df),V.af.push(a),V.xh||(Nb.push(V.uh),V.xh=!0);else for(var b=0;b<V.af.length;++b)V.af[b].target==a.target&&V.af[b].Xe==a.Xe&&hd(b--);return 0}
function od(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var V={Dh:0,ag:0,fg:0,Rf:0,rg:0,og:0,Zf:0,Sh:0,hi:0,Rh:0,$f:0,jg:0,qg:0,ng:0,uh(){for(;V.af.length;)hd(V.af.length-1);V.wf=[]},bg:0,wf:[],af:[],wh:(a,b)=>{for(var c=0;c<V.af.length;++c)V.af[c].target!=a||b&&b!=V.af[c].Xe||hd(c--)},li(a){var b=!1;for(let c=0;c<V.af.length;++c){let d=V.af[c];d.target===a.target&&d.cf===a.cf&&d.$e===a.$e&&d.ef===a.ef&&(hd(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},pd=[0,globalThis.document??0,globalThis.window??
0],W=a=>{a=a>2?a?t(v,a):"":a;return pd[a]||globalThis.document?.querySelector(a)},rd=a=>{var b=Ra(a)+1,c=qd(b);y(a,v,c,b);return c},ud=a=>{var b=sd(),c=qd(8),d=c+4;a=rd(a.id);if(a=W(a))w[c>>2]=a.width,w[d>>2]=a.height;c=[w[c>>2],w[d>>2]];td(b);return c},vd=(a,b,c)=>{a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0},wd=(a,b,c)=>{if(a.Oh){var d=sd();a=rd(a.id);vd(a,b,c);td(d)}else a.width=b,a.height=c},xd=0,yd=a=>{function b(){(document.fullscreenElement??document.webkitFullscreenElement)||(document.removeEventListener("fullscreenchange",
b),document.removeEventListener("webkitfullscreenchange",b),wd(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=u,a.style.paddingBottom=A,a.style.marginLeft=I,a.style.marginRight=K,a.style.marginTop=N,a.style.marginBottom=la,document.body.style.margin=sa,document.documentElement.style.overflow=ma,document.body.scroll=Vb,a.style.imageRendering=
R,a.Ef&&a.Ef.tf.viewport(0,0,d,e),xd.If&&X(xd.If,37,0,xd.wg))}var c=ud(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,u=a.style.paddingTop,A=a.style.paddingBottom,I=a.style.marginLeft,K=a.style.marginRight,N=a.style.marginTop,la=a.style.marginBottom,sa=document.body.style.margin,ma=document.documentElement.style.overflow,Vb=document.body.scroll,R=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},zd=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Ad=a=>pd.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Bd=(a,b)=>{if(b.Sf!=0||b.Jf!=0){yd(a);var c=b.yh?innerWidth:screen.width,d=b.yh?innerHeight:screen.height,e=Ad(a),f=e.width;e=e.height;var g=ud(a),l=g[0];g=g[1];b.Sf==3?(zd(a,(d-e)/2,(c-f)/2),c=f,d=e):b.Sf==2&&(c*g<l*d?(f=g*c/l,zd(a,(d-f)/2,0),d=f):(f=l*d/g,zd(a,0,(c-f)/
2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.Cg==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");n=b.Jf==2?devicePixelRatio:
1;b.Jf!=0&&(c=c*n|0,d=d*n|0,wd(a,c,d),a.Ef&&a.Ef.tf.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return V.fullscreenEnabled()?-3:-1;xd=b;b.If&&X(b.If,37,0,b.wg);return 0},Cd=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Dd=a=>{var b=document.fullscreenElement??document.webkitFullscreenElement,c=!!b;z[a]=c;z[a+1]=V.fullscreenEnabled();
var d=c?b:V.th,e=d?.id??"";y(od(d),v,a+2,128);y(e,v,a+130,128);w[a+260>>2]=d?.clientWidth??0;w[a+264>>2]=d?.clientHeight??0;w[a+268>>2]=screen.width;w[a+272>>2]=screen.height;c&&(V.th=b)},Ed=(a,b)=>{U[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)U[a+c*8+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+c+1040]=b.buttons[c].pressed,U[a+c*8+528>>3]=b.buttons[c].value;z[a+1104]=b.connected;w[a+1108>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;y(b.id,v,a+1112,64);y(b.mapping,
v,a+1176,64)},Fd=[],Gd=(a,b,c,d,e,f,g,l)=>{b=P[b];if(a=O[a](b,c))d=l&&y(a.name,v,l,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},Y,Hd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(S||=1280);return;case 36345:d=0;break;case 34466:var e=O.getParameter(34467);d=e?e.length:0}if(d===void 0)switch(e=O.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":S||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:S||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+a*4>>2]=e[a];break;case 2:Y[b+a*4>>2]=e[a];break;case 4:z[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){S||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:S||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;F[b>>2]=c;F[b+4>>2]=(c-F[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:Y[b>>2]=d;break;case 4:z[b]=d?1:0}}else S||=1281},Id=(a,b,c)=>{if(c){a=O.pf.getQueryObjectEXT(Bc[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;F[c>>2]=d;F[c+4>>2]=(d-F[c>>2])/4294967296}else S||=1281},Jd=(a,b,c)=>{if(c){a=O.pf.getQueryObjectEXT(Bc[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;w[c>>2]=d}else S||=1281},Kd=()=>{var a=uc(O);return a=a.concat(a.map(b=>"GL_"+b))},Ld=a=>a.slice(-1)=="]"&&
a.lastIndexOf("["),Md=a=>{var b=a.Gf,c=a.Og,d;if(!b){a.Gf=b={};a.Ng={};var e=O.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=O.getActiveUniform(a,d);var g=f.name;f=f.size;var l=Ld(g);l=l>0?g.slice(0,l):g;var n=a.pg;a.pg+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Ng[n++]=l}}},Z=(a,b)=>{if(a){var c=a.Gf[b];typeof c=="number"&&(a.Gf[b]=c=O.getUniformLocation(a,a.Ng[b]+(c>0?`[${c}]`:"")));return c}S||=1282},Nd=(a,b,c,d)=>{if(c)if(a=P[a],Md(a),a=O.getUniform(a,Z(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:w[c>>
2]=a;break;case 2:Y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+b*4>>2]=a[b];break;case 2:Y[c+b*4>>2]=a[b]}else S||=1281},Od=(a,b,c,d)=>{if(c)if(a=O.getVertexAttrib(a,b),b==34975)w[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a=="boolean")switch(d){case 0:w[c>>2]=a;break;case 2:Y[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+b*4>>2]=a[b];break;case 2:Y[c+b*4>>2]=a[b];break;case 5:w[c+b*4>>2]=Math.fround(a[b])}else S||=1281},Pd,Qd=(a,
b,c,d,e)=>{a-=5120;a=a==1?v:a==4?w:a==6?Y:a==5||a==28922?F:Pd;b=d*(({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(Ec||c)+Dc-1&-Dc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Rd=[],Sd=[],Td=(a,b)=>{if(!V.fullscreenEnabled())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ld()?Bd(a,b):b.zg?(jd(Bd,1,[a,b]),1):-2:-3:-4},Ud=()=>{try{if(navigator.getGamepads)return(V.Nf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=
null}return-1},Vd=(a,b)=>{var c={target:W(2),Xe:"beforeunload",cf:28,ef:a,$e:b,hf:d=>{var e=X(b,28,0,a);e&&=e?t(v,e):"";if(e)return d.preventDefault(),d.returnValue=e},df:!0};return nd(c)},Wd=(a,b,c,d,e,f)=>{V.Zf||(V.Zf=T(256));a={target:W(a),Xe:f,cf:e,ef:b,$e:d,hf:g=>{var l=g.target.id??"",n=V.Zf;y(od(g.target),v,n+0,128);y(l,v,n+128,128);X(d,e,n,b)&&g.preventDefault()},df:c};return nd(a)},Xd=(a,b,c,d,e)=>{V.$f||(V.$f=T(276));return nd({target:a,Xe:e,cf:19,ef:b,$e:d,hf:f=>{var g=V.$f;Dd(g);X(d,19,
g,b)&&f.preventDefault()},df:c})},Yd=(a,b,c,d,e)=>{V.ag||(V.ag=T(1240));b={target:W(2),Hf:!0,Xe:e,cf:d,ef:a,$e:c,hf:f=>{var g=V.ag;Ed(g,f.gamepad);X(c,d,g,a)&&f.preventDefault()},df:b};return nd(b)},Zd=(a,b,c,d,e,f)=>{V.fg||(V.fg=T(160));a={target:W(a),Xe:f,cf:e,ef:b,$e:d,hf:g=>{var l=V.fg;U[l>>3]=g.timeStamp;var n=l>>2;w[n+2]=g.location;z[l+12]=g.ctrlKey;z[l+13]=g.shiftKey;z[l+14]=g.altKey;z[l+15]=g.metaKey;z[l+16]=g.repeat;w[n+5]=g.charCode;w[n+6]=g.keyCode;w[n+7]=g.which;y(g.key??"",v,l+32,32);
y(g.code??"",v,l+64,32);y(g.char??"",v,l+96,32);y(g.locale??"",v,l+128,32);X(d,e,l,b)&&g.preventDefault()},df:c};return nd(a)},$d=(a,b,c)=>{U[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;z[a+24]=b.ctrlKey;z[a+25]=b.shiftKey;z[a+26]=b.altKey;z[a+27]=b.metaKey;H[d*2+14]=b.button;H[d*2+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=Ad(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},ae=(a,b,c,d,e,f)=>{V.Rf||(V.Rf=T(64));a=W(a);return nd({target:a,
Hf:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",Xe:f,cf:e,ef:b,$e:d,hf:g=>{$d(V.Rf,g,a);X(d,e,V.Rf,b)&&g.preventDefault()},df:c})},be=(a,b,c,d)=>{V.jg||(V.jg=T(257));return nd({target:a,Xe:"pointerlockchange",cf:20,ef:b,$e:d,hf:e=>{var f=V.jg,g=document.pointerLockElement;z[f]=!!g;var l=g?.id??"";y(od(g),v,f+1,128);y(l,v,f+129,128);X(d,20,f,b)&&e.preventDefault()},df:c})},ce=(a,b,c,d)=>{V.og||(V.og=T(36));a=W(a);return nd({target:a,Xe:"resize",cf:10,ef:b,$e:d,hf:e=>{if(e.target==a){var f=document.body;
if(f){var g=V.og;w[g>>2]=0;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset|0;w[g+32>>2]=pageYOffset|0;X(d,10,g,b)&&e.preventDefault()}}},df:c})},de=(a,b,c,d,e,f)=>{V.ng||(V.ng=T(1552));a=W(a);return nd({target:a,Hf:f=="touchstart"||f=="touchend",Xe:f,cf:e,ef:b,$e:d,hf:g=>{var l={},n=g.touches;for(var q of n)q.Fg=q.Ig=0,l[q.identifier]=q;for(var r of g.changedTouches)r.Fg=1,l[r.identifier]=
r;for(var u of g.targetTouches)l[u.identifier].Ig=1;n=V.ng;U[n>>3]=g.timeStamp;z[n+12]=g.ctrlKey;z[n+13]=g.shiftKey;z[n+14]=g.altKey;z[n+15]=g.metaKey;q=n+16;r=Ad(a);u=0;for(let A of Object.values(l))if(l=q>>2,w[l]=A.identifier,w[l+1]=A.screenX,w[l+2]=A.screenY,w[l+3]=A.clientX,w[l+4]=A.clientY,w[l+5]=A.pageX,w[l+6]=A.pageY,z[q+28]=A.Fg,z[q+29]=A.Ig,w[l+8]=A.clientX-(r.left|0),w[l+9]=A.clientY-(r.top|0),q+=48,++u>31)break;w[n+8>>2]=u;X(d,e,n,b)&&g.preventDefault()},df:c})},ee=(a,b,c)=>{var d=pd[1];
V.qg||(V.qg=T(8));return nd({target:d,Xe:"visibilitychange",cf:21,ef:a,$e:c,hf:e=>{var f=V.qg,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);z[f]=document.hidden;w[f+4>>2]=g;X(c,21,f,a)&&e.preventDefault()},df:b})},fe=(a,b,c,d)=>{V.rg||(V.rg=T(96));return nd({target:a,Hf:!0,Xe:"wheel",cf:9,ef:b,$e:d,hf:e=>{var f=V.rg;$d(f,e,a);U[f+64>>3]=e.deltaX;U[f+72>>3]=e.deltaY;U[f+80>>3]=e.deltaZ;w[f+88>>2]=e.deltaMode;X(d,9,f,b)&&e.preventDefault()},df:c})};
class ge{xf=[void 0];bf=[];get(a){return this.xf[a]}has(a){return this.xf[a]!==void 0}}var he=new ge;function ie(a){return he.has(a)?he.get(a):0}function je(a){this.lg||(this.lg=T(520));F[this.lg>>2]=a;return this.lg}
var ke={},me=()=>{if(!le){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea},b;for(b in ke)ke[b]===void 0?delete a[b]:a[b]=ke[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);le=c}return le},le,ne=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})},oe=a=>{try{a()}catch(b){m(b)}};
function pe(a){var b=(...c)=>{qe.push(a);try{return a(...c)}finally{pa||(qe.pop(),re&&se===1&&qe.length===0&&(se=0,J+=1,oe(te),typeof Fibers!="undefined"&&Fibers.pi()))}};ue.set(a,b);return b}var se=0,re=null,ve=0,qe=[],we=new Map,xe=new Map,ue=new Map,ye=0,ze=null,Ae=[];function Be(){return new Promise((a,b)=>{ze={resolve:a,reject:b}})}function Ce(){var a=T(4108),b=a+12;F[a>>2]=b;F[a+4>>2]=b+4096;b=qe[0];if(!we.has(b)){var c=ye++;we.set(b,c);xe.set(c,b)}b=we.get(b);w[a+8>>2]=b;return a}
function De(){var a=xe.get(w[re+8>>2]);a=ue.get(a);--J;return Rb(a)}function Ee(a){if(!pa){if(se===0){var b=!1,c=!1;a((d=0)=>{if(!pa&&(ve=d,b=!0,c)){se=2;oe(()=>Fe(re));typeof Rc!="undefined"&&Lc&&bd();d=!1;try{var e=De()}catch(l){e=l,d=!0}var f=!1;if(!re){var g=ze;g&&(ze=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(se=1,re=Ce(),typeof Rc!="undefined"&&Lc&&ad(),oe(()=>Ge(re)))}else se===2?(se=0,oe(He),Ie(re),re=null,Ae.forEach(Rb)):m(`invalid state: ${se}`);return ve}}
var Je=a=>Ee(async b=>{b(await a())});function Ke(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":z[a]=b;break;case "i8":z[a]=b;break;case "i16":H[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":G[a>>3]=BigInt(b);break;case "float":Y[a>>2]=b;break;case "double":U[a>>3]=b;break;case "*":F[a>>2]=b;break;default:m(`invalid type for setValue: ${c}`)}}x.Qh=(a,b,c,d,e,f,g,l,n,q)=>{qb(a,b,c,d,e,l,n,q).then(f).catch(g)};x.ki=qb;x.rf=Array(4096);x.We(B,{},"/");x.mkdir("/tmp");x.mkdir("/home");
x.mkdir("/home/web_user");(function(){x.mkdir("/dev");Va(x.zf(1,3),{read:()=>0,write:(d,e,f,g)=>g,Ye:()=>0});Db("/dev/null",x.zf(1,3));Ua(x.zf(5,0),Xa);Ua(x.zf(6,0),Ya);Db("/dev/tty",x.zf(5,0));Db("/dev/tty1",x.zf(6,0));var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Na(a),b=a.byteLength);return a[--b]};x.uf("/dev","random",c);x.uf("/dev","urandom",c);x.mkdir("/dev/shm");x.mkdir("/dev/shm/tmp")})();
(function(){x.mkdir("/proc");var a=x.mkdir("/proc/self");x.mkdir("/proc/self/fd");x.We({We(){var b=x.createNode(a,"fd",16895,73);b.Re={Ye:B.Re.Ye};b.Qe={lookup(c,d){c=+d;var e=E(c);c={parent:null,We:{Hg:"fake"},Qe:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(x.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();x.eh={MEMFS:B};h.requestAnimationFrame=dd;h.pauseMainLoop=ad;h.resumeMainLoop=bd;for(let a=0;a<32;++a)Fd.push(Array(a));
for(var Le=new Float32Array(288),Me=0;Me<=288;++Me)Rd[Me]=Le.subarray(0,Me);var Ne=new Int32Array(288);for(Me=0;Me<=288;++Me)Sd[Me]=Ne.subarray(0,Me);h.noExitRuntime&&(Da=h.noExitRuntime);h.print&&(oa=h.print);h.printErr&&(k=h.printErr);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);var Oe=h.preInit;if(Oe)for(typeof Oe=="function"&&(h.preInit=Oe=[Oe]);Oe.length>0;)Oe.shift()();h.addRunDependency=kb;h.removeRunDependency=jb;
h.ccall=(a,b,c,d,e)=>{function f(u){--J;n!==0&&td(n);return b==="string"?u?t(v,u):"":b==="boolean"?!!u:u}var g={string:u=>{var A=0;u!==null&&u!==void 0&&u!==0&&(A=rd(u));return A},array:u=>{var A=qd(u.length);z.set(u,A);return A}};a=h["_"+a];var l=[],n=0;if(d)for(var q=0;q<d.length;q++){var r=g[c[q]];r?(n===0&&(n=sd()),l[q]=r(d[q])):l[q]=d[q]}c=re;d=a(...l);e=e?.async;J+=1;if(re!=c)return Be().then(f);d=f(d);return e?Promise.resolve(d):d};
h.requestFullscreen=function(a,b){function c(){Tb=!1;var f=d.parentNode;(document.fullscreenElement??document.webkitFullscreenElement)===f?(d.exitFullscreen=hc,ec&&d.requestPointerLock(),Tb=!0,fc?(typeof SDL!="undefined"&&(w[SDL.screen>>2]=F[SDL.screen>>2]|8388608),kc(h.canvas),jc()):kc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),fc?(typeof SDL!="undefined"&&(w[SDL.screen>>2]=F[SDL.screen>>2]&-8388609),kc(h.canvas),jc()):kc(d))}ec=a;fc=b;typeof ec=="undefined"&&(ec=!0);typeof fc==
"undefined"&&(fc=!1);var d=h.canvas;dc||(dc=!0,document.addEventListener("fullscreenchange",c),document.addEventListener("webkitfullscreenchange",c));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen??(e.requestFullscreen=(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)??(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null));e.requestFullscreen()};
h.createContext=Zb;h.FS_preloadFile=qb;h.FS_unlink=(...a)=>x.unlink(...a);h.FS_createPath=(...a)=>Gb(...a);h.FS_createDevice=(...a)=>x.uf(...a);h.FS=x;h.FS_createDataFile=(...a)=>pb(...a);h.FS_createLazyFile=(...a)=>Jb(...a);
var Pe={600588:a=>{a=(a?t(v,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");a===null&&(a="i");return a.length===1?a.charCodeAt(0):-1},600803:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,600950:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,601184:a=>{typeof h.SDL2==="undefined"&&(h.SDL2={});var b=h.SDL2;a?b.capture=
{}:b.audio={};b.Ue||(typeof AudioContext!=="undefined"?b.Ue=new AudioContext:typeof webkitAudioContext!=="undefined"&&(b.Ue=new webkitAudioContext),b.Ue&&typeof navigator.userActivation==="undefined"&&ne(b.Ue));return b.Ue===void 0?-1:0},601736:()=>h.SDL2.Ue.sampleRate,601804:(a,b,c,d)=>{function e(){}function f(l){g.capture.lf!==void 0&&(clearInterval(g.capture.lf),g.capture.lf=void 0,g.capture.Cf=void 0);g.capture.hg=g.Ue.createMediaStreamSource(l);g.capture.kf=g.Ue.createScriptProcessor(b,a,1);
g.capture.kf.onaudioprocess=function(n){g!==void 0&&g.capture!==void 0&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Wf=n.inputBuffer,Ca(c,[d]))};g.capture.hg.connect(g.capture.kf);g.capture.kf.connect(g.Ue.destination);g.capture.stream=l}var g=h.SDL2;g.capture.Cf=g.Ue.createBuffer(a,b,g.Ue.sampleRate);g.capture.Cf.getChannelData(0).fill(0);g.capture.lf=setInterval(function(){g.capture.Wf=g.capture.Cf;Ca(c,[d])},b/g.Ue.sampleRate*1E3);navigator.mediaDevices!==void 0&&navigator.mediaDevices.getUserMedia!==
void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):navigator.webkitGetUserMedia!==void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},603497:(a,b,c,d)=>{var e=h.SDL2;e.audio.kf=e.Ue.createScriptProcessor(b,0,a);e.audio.kf.onaudioprocess=function(f){e!==void 0&&e.audio!==void 0&&(e.audio.lf!==void 0&&(clearInterval(e.audio.lf),e.audio.lf=void 0,e.audio.Cf=void 0),e.audio.Lf=f.outputBuffer,Ca(c,[d]))};e.audio.kf.connect(e.Ue.destination);e.Ue.state==="suspended"&&
(e.audio.Cf=e.Ue.createBuffer(a,b,e.Ue.sampleRate),e.audio.Cf.getChannelData(0).fill(0),e.audio.lf=setInterval(function(){typeof navigator.userActivation!=="undefined"&&navigator.userActivation.hasBeenActive&&e.Ue.resume();e.audio.Lf=e.audio.Cf;Ca(c,[d]);e.audio.Lf=void 0},b/e.Ue.sampleRate*1E3))},604672:(a,b)=>{for(var c=h.SDL2,d=c.capture.Wf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Wf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+
" samples vs expected "+b+" samples!";if(d==1)for(var g=0;g<b;++g)Ke(a+g*4,f[g]);else for(g=0;g<b;++g)Ke(a+(g*d+e)*4,f[g])}},605277:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Lf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Lf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=Y[a+(g*d+e)]}},605766:a=>{var b=h.SDL2;if(a){b.capture.lf!==void 0&&clearInterval(b.capture.lf);if(b.capture.stream!==
void 0){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}b.capture.kf!==void 0&&(b.capture.kf.onaudioprocess=function(){},b.capture.kf.disconnect());b.capture.hg!==void 0&&b.capture.hg.disconnect();b.capture=void 0}else b.audio.kf!=void 0&&b.audio.kf.disconnect(),b.audio.lf!==void 0&&clearInterval(b.audio.lf),b.audio=void 0;b.Ue!==void 0&&b.audio===void 0&&b.capture===void 0&&(b.Ue.close(),b.Ue=void 0)},606772:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;
d.Ug!==h.canvas&&(d.Kf=Zb(h.canvas,!1,!0),d.Ug=h.canvas);if(d.w!==a||d.h!==b||d.ih!==d.Kf)d.image=d.Kf.createImageData(a,b),d.w=a,d.h=b,d.ih=d.Kf;a=d.image.data;b=c/4;var e=0;if(typeof CanvasPixelArray!=="undefined"&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Xg!==a&&(d.Wg=new Int32Array(a.buffer),d.Yg=new Uint8Array(a.buffer),d.Xg=a),a=d.Wg,c=a.length,a.set(w.subarray(b,b+c)),a=d.Yg,b=3,e=b+4*c,c%8==0)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Kf.putImageData(d.image,0,0)},608238:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if(typeof CanvasPixelArray!=="undefined"&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var q=w[e];b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>16&
255;b[l+3]=q>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=c===0&&d===0?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=T(c.length+1);y(c,v,d,c.length+1);return d},609226:a=>{h.canvas&&(h.canvas.style.cursor=a?t(v,a):"")},609309:()=>{h.canvas&&(h.canvas.style.cursor="none")},609378:()=>window.innerWidth,609408:()=>window.innerHeight,609439:(a,b)=>{alert((a?t(v,a):"")+"\n\n"+(b?t(v,b):""))}},Qe,T,Ob,Ie,Mb,Za,
td,qd,sd,dynCall_v,dynCall_vi,dynCall_iii,dynCall_vii,X,Ge,te,Fe,He,Re,Se={f:(a,b,c,d)=>m(`Assertion failed: ${a?t(v,a):""}, at: `+[b?b?t(v,b):"":"unknown filename",c,d?d?t(v,d):"":"unknown function"]),L:function(a,b,c){Fa=c;try{var d=E(a);switch(b){case 0:var e=Ga();if(e<0)break;for(;x.streams[e];)e++;return zb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ga(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Ga(),H[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof x==
"undefined"||f.name!=="ErrnoError")throw f;return-f.Te}},Za:function(a,b,c){try{var d=E(a);d.yf||(d.yf=x.readdir(d.path));a=0;var e=x.Ye(d,0,1),f=Math.floor(e/280),g=Math.min(d.yf.length,f+Math.floor(c/280));for(c=f;c<g;c++){var l=d.yf[c];if(l==="."){var n=d.node.id;var q=4}else if(l==="..")n=D(d.path,{parent:!0}).node.id,q=4;else{try{var r=ab(d.node,l)}catch(u){if(u?.Te===28)continue;throw u;}n=r.id;q=(r.mode&61440)===8192?2:C(r.mode)?4:(r.mode&61440)===40960?10:8}G[b+a>>3]=BigInt(n);G[b+a+8>>3]=
BigInt((c+1)*280);H[b+a+16>>1]=280;z[b+a+18]=q;y(l,v,b+a+19,256);a+=280}x.Ye(d,c*280,0);return a}catch(u){if(typeof x=="undefined"||u.name!=="ErrnoError")throw u;return-u.Te}},hb:function(a,b,c){Fa=c;try{var d=E(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.sf.kh){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ga();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var f=0;f<32;f++)z[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.sf.mh)for(e=Ga(),a=[],f=0;f<32;f++)a.push(z[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ga();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=Ga(),x.dg(d,b,e);case 21523:if(!d.tty)return-59;d.tty.sf.nh&&(f=[24,80],e=Ga(),H[e>>1]=f[0],H[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if(typeof x=="undefined"||g.name!=="ErrnoError")throw g;
return-g.Te}},bb:function(a,b,c){try{return b=b?t(v,b):"",b=Kb(a,b),x.mkdir(b,c&-19,0),0}catch(d){if(typeof x=="undefined"||d.name!=="ErrnoError")throw d;return-d.Te}},M:function(a,b,c,d){Fa=d;try{b=b?t(v,b):"";b=Kb(a,b);var e=d?Ga():0;c&64&&(e&=-19);return x.open(b,c,e).fd}catch(f){if(typeof x=="undefined"||f.name!=="ErrnoError")throw f;return-f.Te}},Wa:function(a,b,c,d){try{return b=b?t(v,b):"",d=d?t(v,d):"",b=Kb(a,b),d=Kb(c,d),x.rename(b,d),0}catch(e){if(typeof x=="undefined"||e.name!=="ErrnoError")throw e;
return-e.Te}},Xa:function(a){try{return a=a?t(v,a):"",x.rmdir(a),0}catch(b){if(typeof x=="undefined"||b.name!=="ErrnoError")throw b;return-b.Te}},Va:function(a,b){try{a=a?t(v,a):"";var c=x.stat(a);F[b>>2]=c.dev;F[b+4>>2]=c.mode;F[b+8>>2]=c.nlink;F[b+12>>2]=c.uid;F[b+16>>2]=c.gid;F[b+20>>2]=c.rdev;G[b+24>>3]=BigInt(c.size);w[b+32>>2]=4096;w[b+36>>2]=c.blocks;var d=c.atime.getTime(),e=c.mtime.getTime(),f=c.ctime.getTime();G[b+40>>3]=BigInt(Math.floor(d/1E3));F[b+48>>2]=d%1E3*1E3*1E3;G[b+56>>3]=BigInt(Math.floor(e/
1E3));F[b+64>>2]=e%1E3*1E3*1E3;G[b+72>>3]=BigInt(Math.floor(f/1E3));F[b+80>>2]=f%1E3*1E3*1E3;G[b+88>>3]=BigInt(c.ino);return 0}catch(g){if(typeof x=="undefined"||g.name!=="ErrnoError")throw g;return-g.Te}},Ya:function(a,b,c){try{b=b?t(v,b):"";b=Kb(a,b);if(c)if(c===512)x.rmdir(b);else return-28;else x.unlink(b);return 0}catch(d){if(typeof x=="undefined"||d.name!=="ErrnoError")throw d;return-d.Te}},Ua:a=>{if(ca){if(!a)return 1;a=a?t(v,a):"";if(!a.length)return 0;a=require("node:child_process").ni(a,
[],{mi:!0,stdio:"inherit"});var b=(c,d)=>c<<8|d;return a.status===null?b(0,(c=>{switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15;default:return 2}})(a.signal)):a.status<<8|0}return a?-52:0},$a:function(a,b,c,d,e,f,g){e=e<-9007199254740992||e>9007199254740992?NaN:Number(e);try{var l=E(d),n=x.Af(l,a,e,b,c),q=n.Kg;w[f>>2]=n.xf;F[g>>2]=q;return 0}catch(r){if(typeof x=="undefined"||r.name!=="ErrnoError")throw r;
return-r.Te}},ab:function(a,b,c,d,e,f){f=f<-9007199254740992||f>9007199254740992?NaN:Number(f);try{var g=E(e);if(c&2){c=f;if(!x.isFile(g.node.mode))throw new x.Pe(43);d&2||x.Df(g,v.subarray(a,a+b),c,b,d)}}catch(l){if(typeof x=="undefined"||l.name!=="ErrnoError")throw l;return-l.Te}},Ra:a=>{if(a==12448)return L=12288,1;L=12300;return 0},gb:(a,b,c,d,e)=>{if(a!=62E3)L=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(a==12321)M.alpha=w[b+4>>2]>0;else if(a==12325)M.depth=w[b+4>>2]>0;else if(a==12326)M.stencil=
w[b+4>>2]>0;else if(a==12337)a=w[b+4>>2],M.antialias=a>0;else if(a==12338)a=w[b+4>>2],M.antialias=a==1;else if(a==12544)M.ai=w[b+4>>2]!=12547;else if(a==12344)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&d>0&&(F[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},Ia:(a,b,c,d)=>{if(a!=62E3)return L=12296,0;for(a=1;;){b=w[d>>2];if(b==12440)a=w[d+4>>2];else if(b==12344)break;else return L=12292,0;d+=8}if(a!=2)return L=12293,0;M.Gg=a-1;M.ci=0;qc=ac(h.canvas,M);if(qc!=0)return L=12288,cc(qc),Wb.forEach(e=>e()),
cc(null),62004;L=12297;return 0},Ka:(a,b)=>{if(a!=62E3)return L=12296,0;if(b!=62002)return L=12293,0;L=12288;return 62006},Ja:(a,b)=>{if(a!=62E3)return L=12296,0;if(b!=62004)return L=12294,0;a=qc;Ic===bc[a]&&(Ic=null);typeof V=="object"&&V.wh(bc[a].tf.canvas);bc[a]?.tf.canvas&&(bc[a].tf.canvas.Ef=void 0);bc[a]=null;L=12288;mc==b&&(mc=0);return 1},La:(a,b)=>{if(a!=62E3)return L=12296,0;if(b!=62006)return L=12301,1;nc==b&&(nc=0);oc==b&&(oc=0);L=12288;return 1},nb:(a,b,c,d)=>{if(a!=62E3)return L=12296,
0;if(b!=62002)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return w[d>>2]=M.alpha?32:24,1;case 12321:return w[d>>2]=M.alpha?8:0,1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=M.depth?24:0,1;case 12326:return w[d>>2]=M.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>
2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=M.antialias?4:0,1;case 12338:return w[d>>2]=M.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>
2]=4,1;case 12354:return w[d>>2]=0,1;default:return L=12292,0}},H:a=>{L=12288;return a!=0&&a!=1?0:62E3},Ha:()=>L,Sa:(a,b,c)=>{if(a!=62E3)return L=12296,0;b&&(w[b>>2]=1);c&&(w[c>>2]=4);lc=!0;L=12288;return 1},Ma:(a,b,c,d)=>{if(a!=62E3)return L=12296,0;if(d!=0&&d!=62004)return L=12294,0;if(c!=0&&c!=62006||b!=0&&b!=62006)return L=12301,0;cc(d?qc:null);mc=d;oc=b;nc=c;L=12288;return 1},Ga:(a,b)=>{if(a!=62E3)return L=12296,0;L=12288;if(pc[b])return pc[b];switch(b){case 12371:a=Jc("Emscripten");break;case 12372:a=
Jc("1.4 Emscripten EGL");break;case 12373:a=Jc("");break;case 12429:a=Jc("OpenGL_ES");break;default:return L=12300,0}return pc[b]=a},Na:()=>{if(lc)if(O)if(O.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Oa:(a,b)=>{if(a!=62E3)return L=12296,0;b==0?Zc(0,0):Zc(1,b);L=12288;return 1},_a:a=>{if(a!=62E3)return L=12296,0;oc=nc=mc=0;lc=!1;L=12288;return 1},Qa:()=>{L=12288;return 1},Pa:()=>{L=12288;return 1},T:(a,b,c)=>{b=gd(b,c);return Pe[a](...b)},b:(a,b,c)=>{b=gd(b,c);
return Pe[a](...b)},Ea:(a,b,c)=>{b=gd(b,c);return Pe[a](...b)},U:()=>{ad();Lc=null},N:()=>Date.now(),ya:()=>{if(!V.fullscreenEnabled())return-1;kd(Bd);var a=pd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Da:()=>{kd(Cd);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},Q:a=>{Da=!1;J=0;Pb(a)},h:()=>globalThis.devicePixelRatio??1,c:(a,b,c)=>{a=W(a);if(!a)return-4;
a=Ad(a);U[b>>3]=a.width;U[c>>3]=a.height;return 0},id:a=>{if(!V.fullscreenEnabled())return-1;Dd(a);return 0},R:(a,b)=>{if(a<0||a>=V.Nf.length)return-5;if(!V.Nf[a])return-7;Ed(b,V.Nf[a]);return 0},I:()=>performance.now(),kc:()=>V.Nf.length,Fa:(a,b)=>{w[a>>2]=screen.width;w[b>>2]=screen.height},ca:a=>O.activeTexture(a),ba:(a,b)=>{O.attachShader(P[a],Q[b])},ua:(a,b)=>{O.pf.beginQueryEXT(a,Bc[b])},aa:(a,b,c)=>{O.bindAttribLocation(P[a],b,c?t(v,c):"")},$:(a,b)=>{O.bindBuffer(a,wc[b])},_:(a,b)=>{O.bindFramebuffer(a,
xc[b])},Z:(a,b)=>{O.bindRenderbuffer(a,yc[b])},Y:(a,b)=>{O.bindTexture(a,zc[b])},la:a=>{O.bindVertexArray(Ac[a])},X:(a,b,c,d)=>O.blendColor(a,b,c,d),W:a=>O.blendEquation(a),V:(a,b)=>O.blendEquationSeparate(a,b),Nd:(a,b)=>O.blendFunc(a,b),Md:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),Ld:(a,b,c,d)=>{O.bufferData(a,c?v.subarray(c,c+b):b,d)},Kd:(a,b,c,d)=>{O.bufferSubData(a,b,v.subarray(d,d+c))},Jd:a=>O.checkFramebufferStatus(a),Id:a=>O.clear(a),Hd:(a,b,c,d)=>O.clearColor(a,b,c,d),Gd:a=>O.clearDepth(a),
Fd:a=>O.clearStencil(a),jb:(a,b)=>{O.bh.clipControlEXT(a,b)},Ed:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Dd:a=>{O.compileShader(Q[a])},Cd:(a,b,c,d,e,f,g,l)=>{O.compressedTexImage2D(a,b,c,d,e,f,v.subarray(l,l+g))},Bd:(a,b,c,d,e,f,g,l,n)=>{O.compressedTexSubImage2D(a,b,c,d,e,f,g,v.subarray(n,n+l))},Ad:(a,b,c,d,e,f,g,l)=>O.copyTexImage2D(a,b,c,d,e,f,g,l),zd:(a,b,c,d,e,f,g,l)=>O.copyTexSubImage2D(a,b,c,d,e,f,g,l),yd:()=>{var a=Fc(P),b=O.createProgram();b.name=a;b.Qf=b.Of=b.Pf=0;b.pg=1;P[a]=b;return a},
xd:a=>{var b=Fc(Q);Q[b]=O.createShader(a);return b},wd:a=>O.cullFace(a),vd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2],e=wc[d];e&&(O.deleteBuffer(e),e.name=0,wc[d]=null)}},ud:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+c*4>>2],e=xc[d];e&&(O.deleteFramebuffer(e),e.name=0,xc[d]=null)}},sd:a=>{if(a){var b=P[a];b?(O.deleteProgram(b),b.name=0,P[a]=null):S||=1281}},wa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2],e=Bc[d];e&&(O.pf.deleteQueryEXT(e),Bc[d]=null)}},rd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+
c*4>>2],e=yc[d];e&&(O.deleteRenderbuffer(e),e.name=0,yc[d]=null)}},qd:a=>{if(a){var b=Q[a];b?(O.deleteShader(b),Q[a]=null):S||=1281}},pd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2],e=zc[d];e&&(O.deleteTexture(e),e.name=0,zc[d]=null)}},ka:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+c*4>>2];O.deleteVertexArray(Ac[d]);Ac[d]=null}},od:a=>O.depthFunc(a),nd:a=>{O.depthMask(!!a)},md:(a,b)=>O.depthRange(a,b),ld:(a,b)=>{O.detachShader(P[a],Q[b])},kd:a=>O.disable(a),jd:a=>{O.disableVertexAttribArray(a)},hd:(a,
b,c)=>{O.drawArrays(a,b,c)},ga:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},ha:(a,b)=>{for(var c=Fd[a],d=0;d<a;d++)c[d]=w[b+d*4>>2];O.drawBuffers(c)},gd:(a,b,c,d)=>{O.drawElements(a,b,c,d)},fa:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},fd:a=>O.enable(a),ed:a=>{O.enableVertexAttribArray(a)},ta:a=>{O.pf.endQueryEXT(a)},dd:()=>O.finish(),cd:()=>O.flush(),bd:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,yc[d])},ad:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,zc[d],e)},$c:a=>O.frontFace(a),_c:(a,b)=>
{Gc(a,b,"createBuffer",wc)},Xc:(a,b)=>{Gc(a,b,"createFramebuffer",xc)},xa:(a,b)=>{for(var c=0;c<a;c++){var d=O.pf.createQueryEXT();if(!d){for(S||=1282;c<a;)w[b+c++*4>>2]=0;break}var e=Fc(Bc);d.name=e;Bc[e]=d;w[b+c*4>>2]=e}},Wc:(a,b)=>{Gc(a,b,"createRenderbuffer",yc)},Vc:(a,b)=>{Gc(a,b,"createTexture",zc)},ja:(a,b)=>{Gc(a,b,"createVertexArray",Ac)},Yc:a=>O.generateMipmap(a),Uc:(a,b,c,d,e,f,g)=>Gd("getActiveAttrib",a,b,c,d,e,f,g),Tc:(a,b,c,d,e,f,g)=>Gd("getActiveUniform",a,b,c,d,e,f,g),Sc:(a,b,c,d)=>
{a=O.getAttachedShaders(P[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+b*4>>2]=Q.indexOf(a[b])},Rc:(a,b)=>O.getAttribLocation(P[a],b?t(v,b):""),Qc:(a,b)=>Hd(a,b,4),Pc:(a,b,c)=>{c?w[c>>2]=O.getBufferParameter(a,b):S||=1281},Oc:()=>{var a=O.getError()||S;S=0;return a},Nc:(a,b)=>Hd(a,b,2),Mc:(a,b,c,d)=>{a=O.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Lc:(a,b)=>Hd(a,b,0),Jc:(a,b,c,d)=>{a=O.getProgramInfoLog(P[a]);
a===null&&(a="(unknown error)");b=b>0&&d?y(a,v,d,b):0;c&&(w[c>>2]=b)},Kc:(a,b,c)=>{if(c)if(a>=vc)S||=1281;else if(a=P[a],b==35716)a=O.getProgramInfoLog(a),a===null&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(b==35719){if(!a.Qf){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Qf=Math.max(a.Qf,O.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.Qf}else if(b==35722){if(!a.Of)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.Of=Math.max(a.Of,O.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Of}else if(b==
35381){if(!a.Pf)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Pf=Math.max(a.Pf,O.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Pf}else w[c>>2]=O.getProgramParameter(a,b);else S||=1281},na:Id,qa:Jd,ma:Id,pa:Jd,ra:(a,b,c)=>{c?w[c>>2]=O.pf.getQueryEXT(a,b):S||=1281},Ic:(a,b,c)=>{c?w[c>>2]=O.getRenderbufferParameter(a,b):S||=1281},Gc:(a,b,c,d)=>{a=O.getShaderInfoLog(Q[a]);a===null&&(a="(unknown error)");b=b>0&&d?y(a,v,d,b):0;c&&(w[c>>2]=b)},Fc:(a,b,c,d)=>{a=O.getShaderPrecisionFormat(a,b);w[c>>
2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},Ec:(a,b,c,d)=>{if(a=O.getShaderSource(Q[a]))b=b>0&&d?y(a,v,d,b):0,c&&(w[c>>2]=b)},Hc:(a,b,c)=>{c?b==35716?(a=O.getShaderInfoLog(Q[a]),a===null&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):b==35720?(a=O.getShaderSource(Q[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=O.getShaderParameter(Q[a],b):S||=1281},Dc:a=>{var b=Cc[a];if(!b){switch(a){case 7939:b=Jc(Kd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=O.getParameter(a))||(S||=1280);
b=b?Jc(b):0;break;case 7938:b=Jc(`OpenGL ES 2.0 (${O.getParameter(7938)})`);break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Jc(b);break;default:S||=1280}Cc[a]=b}return b},Cc:(a,b,c)=>{c?Y[c>>2]=O.getTexParameter(a,b):S||=1281},Bc:(a,b,c)=>{c?w[c>>2]=O.getTexParameter(a,b):S||=1281},yc:(a,b)=>{b=b?t(v,b):"";if(a=P[a]){Md(a);var c=a.Gf,d=0,e=b,f=Ld(b);f>0&&(d=b.slice(f+
1),d=parseInt(d)>>>0,e=b.slice(0,f));if((f=a.Og[e])&&d<f[0]&&(d+=f[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else S||=1281;return-1},Ac:(a,b,c)=>{Nd(a,b,c,2)},zc:(a,b,c)=>{Nd(a,b,c,0)},vc:(a,b,c)=>{c?w[c>>2]=O.getVertexAttribOffset(a,b):S||=1281},xc:(a,b,c)=>{Od(a,b,c,2)},wc:(a,b,c)=>{Od(a,b,c,5)},uc:(a,b)=>O.hint(a,b),tc:a=>(a=wc[a])?O.isBuffer(a):0,sc:a=>O.isEnabled(a),rc:a=>(a=xc[a])?O.isFramebuffer(a):0,qc:a=>(a=P[a])?O.isProgram(a):0,va:a=>(a=Bc[a])?O.pf.isQueryEXT(a):0,pc:a=>(a=yc[a])?
O.isRenderbuffer(a):0,oc:a=>(a=Q[a])?O.isShader(a):0,nc:a=>(a=zc[a])?O.isTexture(a):0,ia:a=>(a=Ac[a])?O.isVertexArray(a):0,mc:a=>O.lineWidth(a),lc:a=>{a=P[a];O.linkProgram(a);a.Gf=0;a.Og={}},jc:(a,b)=>{a==3317?Dc=b:a==3314&&(Ec=b);O.pixelStorei(a,b)},ib:(a,b)=>{O.Ah.polygonModeWEBGL(a,b)},ic:(a,b)=>O.polygonOffset(a,b),kb:(a,b,c)=>{O.dh.polygonOffsetClampEXT(a,b,c)},sa:(a,b)=>{O.pf.queryCounterEXT(Bc[a],b)},hc:(a,b,c,d,e,f,g)=>{(g=Qd(f,e,c,d,g))?O.readPixels(a,b,c,d,e,f,g):S||=1280},gc:()=>{},fc:(a,
b,c,d)=>O.renderbufferStorage(a,b,c,d),ec:(a,b)=>{O.sampleCoverage(a,!!b)},dc:(a,b,c,d)=>O.scissor(a,b,c,d),cc:()=>{S||=1280},bc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=F[c+f*4>>2])?t(v,g,d?F[d+f*4>>2]:void 0):"";e+=g}O.shaderSource(Q[a],e)},ac:(a,b,c)=>O.stencilFunc(a,b,c),$b:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),_b:a=>O.stencilMask(a),Zb:(a,b)=>O.stencilMaskSeparate(a,b),Yb:(a,b,c)=>O.stencilOp(a,b,c),Xb:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Wb:(a,b,c,d,e,f,g,l,n)=>{n=n?Qd(l,g,d,e,
n):null;O.texImage2D(a,b,c,d,e,f,g,l,n)},Vb:(a,b,c)=>O.texParameterf(a,b,c),Ub:(a,b,c)=>{O.texParameterf(a,b,Y[c>>2])},Tb:(a,b,c)=>O.texParameteri(a,b,c),Sb:(a,b,c)=>{O.texParameteri(a,b,w[c>>2])},Rb:(a,b,c,d,e,f,g,l,n)=>{n=n?Qd(l,g,e,f,n):null;O.texSubImage2D(a,b,c,d,e,f,g,l,n)},Qb:(a,b)=>{O.uniform1f(Z(O.Ve,a),b)},Pb:(a,b,c)=>{if(b<=288)for(var d=Rd[b],e=0;e<b;++e)d[e]=Y[c+4*e>>2];else d=Y.subarray(c>>2,c+b*4>>2);O.uniform1fv(Z(O.Ve,a),d)},Ob:(a,b)=>{O.uniform1i(Z(O.Ve,a),b)},Nb:(a,b,c)=>{if(b<=
288)for(var d=Sd[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+b*4>>2);O.uniform1iv(Z(O.Ve,a),d)},Mb:(a,b,c)=>{O.uniform2f(Z(O.Ve,a),b,c)},Lb:(a,b,c)=>{if(b<=144){b*=2;for(var d=Rd[b],e=0;e<b;e+=2)d[e]=Y[c+4*e>>2],d[e+1]=Y[c+(4*e+4)>>2]}else d=Y.subarray(c>>2,c+b*8>>2);O.uniform2fv(Z(O.Ve,a),d)},Kb:(a,b,c)=>{O.uniform2i(Z(O.Ve,a),b,c)},Jb:(a,b,c)=>{if(b<=144){b*=2;for(var d=Sd[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+b*8>>2);O.uniform2iv(Z(O.Ve,a),
d)},Ib:(a,b,c,d)=>{O.uniform3f(Z(O.Ve,a),b,c,d)},Hb:(a,b,c)=>{if(b<=96){b*=3;for(var d=Rd[b],e=0;e<b;e+=3)d[e]=Y[c+4*e>>2],d[e+1]=Y[c+(4*e+4)>>2],d[e+2]=Y[c+(4*e+8)>>2]}else d=Y.subarray(c>>2,c+b*12>>2);O.uniform3fv(Z(O.Ve,a),d)},Gb:(a,b,c,d)=>{O.uniform3i(Z(O.Ve,a),b,c,d)},Fb:(a,b,c)=>{if(b<=96){b*=3;for(var d=Sd[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+b*12>>2);O.uniform3iv(Z(O.Ve,a),d)},Eb:(a,b,c,d,e)=>{O.uniform4f(Z(O.Ve,a),b,c,d,
e)},Db:(a,b,c)=>{if(b<=72){var d=Rd[4*b],e=Y;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=Y.subarray(c>>2,c+b*16>>2);O.uniform4fv(Z(O.Ve,a),d)},Cb:(a,b,c,d,e)=>{O.uniform4i(Z(O.Ve,a),b,c,d,e)},Bb:(a,b,c)=>{if(b<=72){b*=4;for(var d=Sd[b],e=0;e<b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2]}else d=w.subarray(c>>2,c+b*16>>2);O.uniform4iv(Z(O.Ve,a),d)},Ab:(a,b,c,d)=>{if(b<=72){b*=4;for(var e=Rd[b],
f=0;f<b;f+=4)e[f]=Y[d+4*f>>2],e[f+1]=Y[d+(4*f+4)>>2],e[f+2]=Y[d+(4*f+8)>>2],e[f+3]=Y[d+(4*f+12)>>2]}else e=Y.subarray(d>>2,d+b*16>>2);O.uniformMatrix2fv(Z(O.Ve,a),!!c,e)},zb:(a,b,c,d)=>{if(b<=32){b*=9;for(var e=Rd[b],f=0;f<b;f+=9)e[f]=Y[d+4*f>>2],e[f+1]=Y[d+(4*f+4)>>2],e[f+2]=Y[d+(4*f+8)>>2],e[f+3]=Y[d+(4*f+12)>>2],e[f+4]=Y[d+(4*f+16)>>2],e[f+5]=Y[d+(4*f+20)>>2],e[f+6]=Y[d+(4*f+24)>>2],e[f+7]=Y[d+(4*f+28)>>2],e[f+8]=Y[d+(4*f+32)>>2]}else e=Y.subarray(d>>2,d+b*36>>2);O.uniformMatrix3fv(Z(O.Ve,a),!!c,
e)},yb:(a,b,c,d)=>{if(b<=18){var e=Rd[16*b],f=Y;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=Y.subarray(d>>2,d+b*64>>2);O.uniformMatrix4fv(Z(O.Ve,a),!!c,e)},xb:a=>{a=P[a];O.useProgram(a);O.Ve=a},wb:a=>{O.validateProgram(P[a])},vb:(a,b)=>O.vertexAttrib1f(a,b),ub:(a,
b)=>{O.vertexAttrib1f(a,Y[b>>2])},tb:(a,b,c)=>O.vertexAttrib2f(a,b,c),sb:(a,b)=>{O.vertexAttrib2f(a,Y[b>>2],Y[b+4>>2])},rb:(a,b,c,d)=>O.vertexAttrib3f(a,b,c,d),qb:(a,b)=>{O.vertexAttrib3f(a,Y[b>>2],Y[b+4>>2],Y[b+8>>2])},pb:(a,b,c,d,e)=>O.vertexAttrib4f(a,b,c,d,e),ob:(a,b)=>{O.vertexAttrib4f(a,Y[b>>2],Y[b+4>>2],Y[b+8>>2],Y[b+12>>2])},ea:(a,b)=>{O.vertexAttribDivisor(a,b)},mb:(a,b,c,d,e,f)=>{O.vertexAttribPointer(a,b,c,!!d,e,f)},lb:(a,b,c,d)=>O.viewport(a,b,c,d),k:()=>1,Zc:(a,b)=>Td(a,{Sf:0,Jf:0,Cg:0,
zg:b,Nh:2}),Aa:(a,b,c)=>Td(a,{Sf:w[c>>2],Jf:w[c+4>>2],Cg:w[c+8>>2],zg:b,If:w[c+12>>2],wg:w[c+16>>2]}),G:(a,b)=>{a=W(a);return a?a.requestPointerLock?ld()?Cd(a):b?(jd(Cd,2,[a]),1):-2:-1:-4},Ta:()=>{m("OOM")},S:Ud,l:(a,b,c)=>typeof onbeforeunload=="undefined"?-1:c!==1?-5:Vd(a,b),x:(a,b,c,d)=>Wd(a,b,c,d,12,"blur"),g:vd,j:(a,b,c)=>{a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},y:(a,b,c,d)=>Wd(a,b,c,d,13,"focus"),o:(a,b,c,d)=>{if(!V.fullscreenEnabled())return-1;a=W(a);if(!a)return-4;
Xd(a,b,c,d,"webkitfullscreenchange");return Xd(a,b,c,d,"fullscreenchange")},P:(a,b,c)=>Ud()?-1:Yd(a,b,c,26,"gamepadconnected"),O:(a,b,c)=>Ud()?-1:Yd(a,b,c,27,"gamepaddisconnected"),r:(a,b,c,d)=>Zd(a,b,c,d,2,"keydown"),p:(a,b,c,d)=>Zd(a,b,c,d,1,"keypress"),q:(a,b,c,d)=>Zd(a,b,c,d,3,"keyup"),td:(a,b,c)=>{$c(()=>dynCall_v(a),b,c)},E:(a,b,c,d)=>ae(a,b,c,d,5,"mousedown"),B:(a,b,c,d)=>ae(a,b,c,d,33,"mouseenter"),A:(a,b,c,d)=>ae(a,b,c,d,34,"mouseleave"),F:(a,b,c,d)=>ae(a,b,c,d,8,"mousemove"),C:(a,b,c,d)=>
ae(a,b,c,d,6,"mouseup"),s:(a,b,c,d)=>document.body?.requestPointerLock?(a=W(a))?be(a,b,c,d):-4:-1,n:(a,b,c,d)=>ce(a,b,c,d),t:(a,b,c,d)=>de(a,b,c,d,25,"touchcancel"),v:(a,b,c,d)=>de(a,b,c,d,23,"touchend"),u:(a,b,c,d)=>de(a,b,c,d,24,"touchmove"),w:(a,b,c,d)=>de(a,b,c,d,22,"touchstart"),m:(a,b,c)=>pd[1]?ee(a,b,c):-4,z:(a,b,c,d)=>(a=W(a))?typeof a.onwheel!="undefined"?fe(a,b,c,d):-1:-4,Ba:a=>document.title=a?t(v,a):"",a:function(a){return Je(()=>new Promise(b=>setTimeout(b,a)))},d:(a,b)=>{a=ie(a);if(!a)return-3;
H[b>>1]=a.readyState;return 0},Ca:a=>{if(!globalThis.WebSocket)return-1;if(!a)return-5;var b=(b=F[a>>2])?t(v,b):"";a=(a=F[a+4>>2])?new WebSocket(b,(a?t(v,a):"").split(",")):new WebSocket(b);a.binaryType="arraybuffer";b=he.bf.pop()??he.xf.length;he.xf[b]=a;return b},D:(a,b,c)=>{a=ie(a);if(!a)return-3;a.send(v.subarray(b,b+c));return 0},oa:(a,b,c)=>{var d=ie(a);if(!d)return-3;d.onclose=e=>{var f=je(a);z[f+4]=e.wasClean;H[f+6>>1]=e.code;y(e.reason,v,f+8,512);X(c,0,f,b)};return 0},da:(a,b,c)=>{var d=
ie(a);if(!d)return-3;d.onerror=()=>{var e=je(a);X(c,0,e,b)};return 0},Od:(a,b,c)=>{var d=ie(a);if(!d)return-3;d.onmessage=e=>{var f=typeof e.data=="string";if(f)var g=Jc(e.data),l=Ra(e.data)+1;else l=e.data.byteLength,g=T(l),z.set(new Uint8Array(e.data),g);e=je(a);F[e+4>>2]=g;w[e+8>>2]=l;z[e+12]=f;X(c,0,e,b);Ie(g)};return 0},za:(a,b,c)=>{var d=ie(a);if(!d)return-3;d.onopen=()=>{var e=je(a);X(c,0,e,b)};return 0},eb:(a,b)=>{var c=0,d=0,e;for(e of me()){var f=b+c;F[a+d>>2]=f;c+=y(e,v,f,Infinity)+1;d+=
4}return 0},fb:(a,b)=>{var c=me();F[a>>2]=c.length;a=0;for(var d of c)a+=Ra(d)+1;F[b>>2]=a;return 0},e:Pb,i:function(a){try{var b=E(a);x.close(b);return 0}catch(c){if(typeof x=="undefined"||c.name!=="ErrnoError")throw c;return c.Te}},db:function(a,b){try{var c=E(a);z[b]=c.tty?2:C(c.mode)?3:(c.mode&61440)===40960?7:4;H[b+2>>1]=0;G[b+8>>3]=BigInt(0);G[b+16>>3]=BigInt(0);return 0}catch(d){if(typeof x=="undefined"||d.name!=="ErrnoError")throw d;return d.Te}},J:function(a,b,c,d){try{a:{var e=E(a);a=b;
for(var f,g=b=0;g<c;g++){var l=F[a>>2],n=F[a+4>>2];a+=8;try{var q=x.read(e,z,l,n,f)}catch(u){if(b>0&&u instanceof x.Pe&&(u.Te==6||u.Te==6))break;throw u;}if(q<0){var r=-1;break a}b+=q;if(q<n)break;typeof f!="undefined"&&(f+=q)}r=b}F[d>>2]=r;return 0}catch(u){if(typeof x=="undefined"||u.name!=="ErrnoError")throw u;return u.Te}},cb:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=E(a);x.Ye(e,b,c);G[d>>3]=BigInt(e.position);e.yf&&b===0&&c===0&&
(e.yf=null);return 0}catch(f){if(typeof x=="undefined"||f.name!=="ErrnoError")throw f;return f.Te}},K:function(a,b,c,d){try{var e=E(a);a=b;if(c==1)var f=x.write(e,z,F[a>>2],F[a+4>>2],void 0);else{for(var g=b=0,l=a;g<c;g++,l+=8)b+=F[l+4>>2];var n=new Uint8Array(b);for(g=l=0;g<c;g++,a+=8){var q=F[a>>2],r=F[a+4>>2];n.set(v.subarray(q,q+r),l);l+=r}f=x.write(e,n,0,b,void 0)}F[d>>2]=f;return 0}catch(u){if(typeof x=="undefined"||u.name!=="ErrnoError")throw u;return u.Te}}};
function Te(a=[]){var b=Qe;a.unshift(ea);var c=a.length,d=qd((c+1)*4),e=d,f;for(f of a)F[e>>2]=rd(f),e+=4;F[e>>2]=0;try{var g=b(c,d);Pb(g,!0)}catch(l){Lb(l)}}async function Ue(){var a=da;ta();hb&&await gb();var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));pa||(h.noFSInit||x.cg||x.init(),Ve.Qd(),x.Eg=!1,h.onRuntimeInitialized?.(),h.noInitialRun||Te(a),va())}var Ve;
(async function(){function a(d){var e=Ve=d.exports;d={};for(let [f,g]of Object.entries(e))typeof g=="function"?(e=pe(g),d[f]=e):d[f]=g;d=Ve=d;Qe=h._main=d.Rd;T=d.Sd;Ob=d.Td;Ie=d.Ud;Mb=d.Vd;Za=d.Wd;td=d.Xd;qd=d.Yd;sd=d.Zd;dynCall_v=p.v=d._d;p.viiii=d.$d;p.i=d.ae;dynCall_vi=p.vi=d.be;dynCall_iii=p.iii=d.ce;dynCall_vii=p.vii=d.de;p.ii=d.ee;p.viii=d.fe;p.iiiiii=d.ge;X=p.iiii=d.he;p.iiiii=d.ie;p.vjii=d.je;p.vf=d.ke;p.iiji=d.le;p.iid=d.me;p.di=d.ne;p.viiiii=d.oe;p.iiiiiiii=d.pe;p.iiiiiiiiii=d.qe;p.iiiiiiiiiiiiiiff=
d.re;p.iiiiiiiii=d.se;p.viiiiiii=d.te;p.viiiiiiiiiii=d.ue;p.iiiiiidiiff=d.ve;p.ji=d.we;p.jiji=d.xe;p.vffff=d.ye;p.viiiiiiii=d.ze;p.viiiiiiiii=d.Ae;p.vff=d.Be;p.vfi=d.Ce;p.viif=d.De;p.vif=d.Ee;p.viff=d.Fe;p.vifff=d.Ge;p.viffff=d.He;p.viiiiii=d.Ie;p.vfff=d.Je;p.iidiiiii=d.Ke;Ge=d.Le;te=d.Me;Fe=d.Ne;He=d.Oe;Re=d.Pd;d=Re.buffer;z=new Int8Array(d);H=new Int16Array(d);v=new Uint8Array(d);Pd=new Uint16Array(d);w=new Int32Array(d);F=new Uint32Array(d);Y=new Float32Array(d);U=new Float64Array(d);G=new BigInt64Array(d);
return Ve}var b={a:Se},c=h.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});xa??=h.locateFile?h.locateFile("websockets-doom.wasm",ia):ia+"websockets-doom.wasm";return function(d){return a(d.instance)}(await Aa(b))})().then(()=>Ue());
