// Generated by cpp4r: do not edit by hand
// clang-format off


#include "cpp4r/declarations.hpp"
#include <R_ext/Visibility.h>

// main.cpp
std::string tabler_hash_raw(raws x);
extern "C" SEXP _tabler_tabler_hash_raw(SEXP x) {
  BEGIN_CPP4R
    return cpp4r::as_sexp(tabler_hash_raw(cpp4r::as_cpp<cpp4r::decay_t<raws>>(x)));
  END_CPP4R
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_tabler_tabler_hash_raw", (DL_FUNC) &_tabler_tabler_hash_raw, 1},
    {NULL, NULL, 0}
};
}
extern "C" attribute_visible void R_init_tabler(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
