# Generated by cpp4r: do not edit by hand

#' @title Hash Raw Bytes (C++)
#' @description Computes a fast, well-mixed 128-bit (32 hex character) hash of
#'   a raw vector. Used internally by `.tabler_cache_key()` to turn the raw
#'   bytes from `serialize(x, connection = NULL)` into a cachem-compatible
#'   cache key, without depending on `rlang`/`digest` or touching disk (unlike
#'   `tools::md5sum()`, which only hashes files).
#' @param x A raw vector, e.g. the output of `serialize()`.
#' @return A 32-character lowercase hex string.
#' @keywords internal
#' @noRd
tabler_hash_raw <- function(x) {
	.Call(`_tabler_tabler_hash_raw`, x)
}
